### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'dtype'

### ISSUE THREAD

**Issue by km1994** [bentrevett/pytorch-sentiment-analysis#10]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-095550f7e26c> in <module>
     10 
     11 TEXT = data.Field(tokenize='spacy', preprocessing=generate_bigrams)
---> 12 LABEL = data.LabelField(dtype=torch.float)

d:\progrom\python\python\python3\lib\site-packages\torchtext-0.2.3-py3.6.egg\torchtext\data\field.py in __init__(self, **kwargs)
    691         kwargs['unk_token'] = None
    692 
--> 693         super(LabelField, self).__init__(**kwargs)

TypeError: __init__() got an unexpected keyword argument 'dtype'

**Comment by bentrevett** [comment]
You need to update your TorchText. You're using TorchText 0.2.3 and the guide has been updated for TorchText 0.3.
