### ISSUE TITLE
The train_data built from my own dataset after following the Appendix A looks wrong

### ISSUE THREAD

**Issue by mikewakawski** [bentrevett/pytorch-sentiment-analysis#100]
So I downloaded the [sentiment140 dataset](http://help.sentiment140.com/for-students) and I'm trying to try predict the polarity of some tweets bases on that dataset.

Since it's not a PyTorch built-in dataset, I followed your Appendix A notebooks and used a csv file but for some reason after building the vocab and trying to check the train_data variable I get this: ```{'t': ['0'], 'p': ['0']}```

Here's my code:
```
TEXT = data.Field()
POLARITY = data.LabelField()
fields = [('t', TEXT), ('p', POLARITY)]
train_data, valid_data, test_data = data.TabularDataset.splits(
                                        path = 'data',
                                        train = 'train.csv',
                                        validation = 'valid.csv',
                                        test = 'test.csv',
                                        format = 'csv',
                                        fields = fields,
                                        skip_header = True
)
print(vars(train_data[0]))
```

**Comment by bentrevett** [comment]
The .csv file for the dataset you're linking has six columns so your `fields` list needs to have six items, one for each column. The first column is the polarity and the last column is the actual text, so you need `fields` to be:

```py
fields = [('p', POLARITY),
          (None, None),
          (None, None), 
          (None, None),
          (None, None),
          ('t', TEXT)]
```

The tuple of `None` just skips the column. The dataset also doesn't have a header so you don't need `skip_header=True`.
