### ISSUE TITLE
migrating to the new API

### ISSUE THREAD

**Issue by richardxing** [bentrevett/pytorch-sentiment-analysis#101]
Hi, could you migrate from the legacy API to the new API. Thanks a lot!

**Comment by bentrevett** [comment]
I'm working on this currently. Planning to completely re-do all of the tutorials -- change the order and models used -- now that the new API is stable.

**Comment by richardxing** [comment]
Thanks a lot! Looking forward to it!

**Comment by bentrevett** [comment]
Tutorials with the new API are now available, see:
- https://github.com/bentrevett/pytorch-sentiment-analysis/blob/master/1_nbow.ipynb
- https://github.com/bentrevett/pytorch-sentiment-analysis/blob/master/2_lstm.ipynb
- https://github.com/bentrevett/pytorch-sentiment-analysis/blob/master/3_cnn.ipynb
- https://github.com/bentrevett/pytorch-sentiment-analysis/blob/master/4_transformer.ipynb

**Comment by thulieblack** [comment]
Hie, is there a way to import custom data on the new torchtext API, as the _data.TabularDatasets.splits_ is now retired.
Thanks.
