### ISSUE TITLE
.squeeze(1)

### ISSUE THREAD

**Issue by pberko** [bentrevett/pytorch-sentiment-analysis#102]
Hello,

Thanks for the tutortial!

I tried to copy the first rnn (Simple Sentiment Analysis) to Pycharm and run the same code, but I got the error:

`Target size (torch.Size([1, 64])) must be the same as input size (torch.Size([64]))`

on the row 
`loss = criterion(predictions, batch.label)`
  
`  File "/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py", line 2958, in binary_cross_entropy_with_logits
    raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
ValueError: Target size (torch.Size([1, 64])) must be the same as input size (torch.Size([64]))`

after trying to fix that by adding
 `batch.label = batch.label.squeeze(0)`
Althoght the code runs but it does not seem to work:

accuracy stays with 0 and loss is minus:
`Epoch: 01 | Epoch Time: 7m 3s
	Train Loss: -56.793 | Train Acc: 0.00%
	 Val. Loss: -108.977 |  Val. Acc: 0.00%`

**Comment by roiDaniela** [comment]
I have the same problem...

**Comment by bentrevett** [comment]
What version of PyTorch and torchtext are you using?

**Comment by pberko** [comment]
@bentrevett thank you for your response.

In [2]: torchtext.__version__
Out[2]: '0.10.0'

In [4]: torch.__version__
Out[4]: '1.9.0'

**Comment by roiDaniela** [comment]
for me also not working for the versions:
In [2]: torchtext.__version__
Out[2]: '0.10.0'

In [2]: torch.__version__
Out[2]: '1.9.0'

**Comment by roiDaniela** [comment]
Hello @bentrevett 

same happend when downgrade to
![image](https://user-images.githubusercontent.com/11479074/124655825-0cc4de80-dea9-11eb-9033-94f1614df05b.png)

**Comment by pberko** [comment]
worked after 
source ****/venv/Scripts/activate

python -m pip install torch==1.8.0+cpu torchvision==0.9.0+cpu torchaudio==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html

python -m pip install torchtext==0.90

thanks!
