### ISSUE TITLE
train_test_split in LSTM

### ISSUE THREAD

**Issue by huni1023** [bentrevett/pytorch-sentiment-analysis#106]
[https://github.com/bentrevett/pytorch-sentiment-analysis/blob/master/2_lstm.ipynb]

in those jupyter-notebook above, 
i think library for code `train_test_split` isn't called. (cell 7)
Should I using `from sklearn.model_selection import train_test_split` ?

**Comment by bentrevett** [comment]
Why do you think it is not called?

The `train_data` is a HuggingFace datasets Dataset class, which has a `train_test_split` method, see: https://huggingface.co/docs/datasets/package_reference/main_classes.html#datasets.Dataset.train_test_split. This is unrelated to `sklearn`'s `train_test_split` function.

**Comment by huni1023** [comment]
Thanks for your kind response. I will check out details again!
