### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'dtype'

### ISSUE THREAD

**Issue by VerbalCPU** [bentrevett/pytorch-sentiment-analysis#11]
TypeError                                 Traceback (most recent call last)
<ipython-input-4-97d32aa3bb4d> in <module>()
      9 
     10 TEXT = data.Field(tokenize='spacy')
---> 11 LABEL = data.LabelField(dtype=torch.float)

~\AppData\Local\Programs\Python\Python36\lib\site-packages\torchtext\data\field.py in __init__(self, **kwargs)
    691     `None` by default.
    692     """
--> 693 
    694     def __init__(self, **kwargs):
    695         # whichever value is set for sequential and unk_token will be overwritten

TypeError: __init__() got an unexpected keyword argument 'dtype'

I have read the previeus issue and I updated my torchtext but the problem still exists.
Any suggestions?

**Comment by bentrevett** [comment]
Can you try:

```python
import torch
import torchtext
print(torch.__version__)
print(torchtext.__version__)
```

and ensure it's printing out 0.4.1 for Torch 0.3.1 for TorchText?

**Comment by VerbalCPU** [comment]
Even though I had the prepared my machine with the exact results that you are proposing, at first the error persisted but now after a restart it works so thank you for your time!
