### ISSUE TITLE
Can you tell me a method for prediction on batch? Predicting per sentence takes a lot of time.

### ISSUE THREAD

**Issue by kuldeep7688** [bentrevett/pytorch-sentiment-analysis#12]

**Comment by bentrevett** [comment]
Do you mean within the training loop? This is already done on batches of sentences.

**Comment by kuldeep7688** [comment]
No. You have written a function in the end for predicting  on new sentences using the trained model.
I wanted to know whether we can do this batch wise.

Maybe using something like this: (test_data.csv has just sentences)

`test_val_fields = [
        ('text', TEXT), # process it as text
    ]

    test = data.TabularDataset(
        path='test_data.csv',
        format='csv', 
        fields=test_val_fields,
        skip_header=True)
    
    test_iterator = data.BucketIterator(
        test, device=device, 
        batch_size=BATCH_SIZE,
        sort_key=lambda x: len(x.text)
    )`


And using this iterator for predicting.

**Comment by bentrevett** [comment]
Yep, something like that looks good.
