### ISSUE TITLE
Why do not need to zero the hidden tensors?

### ISSUE THREAD

**Issue by TrinaDu** [bentrevett/pytorch-sentiment-analysis#14]

**Comment by bentrevett** [comment]
I'm assuing you mean why am I not creating initial hidden states to tensors of all zeros?

If you check the PyTorch documentation for the LSTM (https://pytorch.org/docs/stable/nn.html#torch.nn.LSTM) you can see:

If *(h_0, c_0)* is not provided, both **h_0** and **c_0** default to zero.

Thus, by not passing a hidden (and cell) state to the self.rnn, we are effectively passing an initial hidden state, h_0, (and initial cell state, c_0) as a tensor of all zeros.
