### ISSUE TITLE
Dimension out of range in the last batch

### ISSUE THREAD

**Issue by littleflow3r** [bentrevett/pytorch-sentiment-analysis#17]
I used my own data and in the last batch of my data (where there were only 1 example), model(batch.text).squeeze(1) causes a dimension out of range error. 
`predictions = model(batch.text).squeeze(1)`
I solved it by not squeeze it in case batch only contains one example. 
But I'm wondering if it happened to anyone else?

**Comment by bentrevett** [comment]
Yep, I think this is an issue with the code. Note how in the `predict_sentiment` functions for notebooks 2, 3 and 4 we do `prediction = torch.sigmoid(model(tensor))` (notice the no `squeeze`). 

I think using a batch size of 1 is quite rare, but I might make a note of it in the tutorials.

Thanks for pointing it out though!

**Comment by littleflow3r** [comment]
It's not that I used batch size 1, it just happened that in my last batch there were only one example. 
Thanks anyway!
