### ISSUE TITLE
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

### ISSUE THREAD

**Issue by teymour-aldridge** [bentrevett/pytorch-sentiment-analysis#2]
I've loaded the file into a colab notebook. When I try to run the first cell of the notebook I get the following: 
`OSError                                   Traceback (most recent call last)
<ipython-input-5-04d5e22ee5a5> in <module>()
     12 torch.cuda.manual_seed(SEED)
     13 
---> 14 TEXT = data.Field(tokenize='spacy')
     15 LABEL = data.LabelField(tensor_type=torch.FloatTensor)
     16 

/usr/local/lib/python3.6/dist-packages/torchtext/data/field.py in __init__(self, sequential, use_vocab, init_token, eos_token, fix_length, tensor_type, preprocessing, postprocessing, lower, tokenize, include_lengths, batch_first, pad_token, unk_token, pad_first, truncate_first)
    148         self.postprocessing = postprocessing
    149         self.lower = lower
--> 150         self.tokenize = get_tokenizer(tokenize)
    151         self.include_lengths = include_lengths
    152         self.batch_first = batch_first

/usr/local/lib/python3.6/dist-packages/torchtext/data/utils.py in get_tokenizer(tokenizer)
     10         try:
     11             import spacy
---> 12             spacy_en = spacy.load('en')
     13             return lambda s: [tok.text for tok in spacy_en.tokenizer(s)]
     14         except ImportError:

/usr/local/lib/python3.6/dist-packages/spacy/__init__.py in load(name, **overrides)
     13     if depr_path not in (True, False, None):
     14         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 15     return util.load_model(name, **overrides)
     16 
     17 

/usr/local/lib/python3.6/dist-packages/spacy/util.py in load_model(name, **overrides)
    117     elif hasattr(name, 'exists'):  # Path or Path-like to model data
    118         return load_model_from_path(name, **overrides)
--> 119     raise IOError(Errors.E050.format(name=name))
    120 
    121 

OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.`

**Comment by teymour-aldridge** [comment]
Thanks!

**Comment by greed2411** [comment]
If nothing else, this issue can be closed.

**Comment by pandikapinata** [comment]
i got same error in Jupyter Notebook, im already installed spacy english use command `python -m spacy download en` but still got same error
please help..

**Comment by bentrevett** [comment]
@pandikapinata I'd first try just making a separate file with the following:
```python
import spacy
spacy_en = spacy.load('en')
```
If this still gives you an error then I would suggest opening an issue on spaCy's GitHub page.
