### ISSUE TITLE
custom word embedding learning

### ISSUE THREAD

**Issue by 404akhan** [bentrevett/pytorch-sentiment-analysis#29]
u can also add a feature of saving final embeddings after the training. And then loading custom embeddings in the following part of the code:
```
TEXT.build_vocab(train_data, max_size=25000, vectors="glove.twitter.27B.100d", unk_init=torch.Tensor.normal_)
```
This might be useful in case of existence of a distant dataset.

![image](https://user-images.githubusercontent.com/21444578/54910270-efadb100-4f26-11e9-8afd-e4b951b29ea0.png ) ![image](https://user-images.githubusercontent.com/21444578/54910249-e3295880-4f26-11e9-85d1-b5d85955bc7a.png )

Full link to the paper:
http://www.aclweb.org/anthology/S17-2094

**Comment by bentrevett** [comment]
I've added an [appendix C notebook](https://github.com/bentrevett/pytorch-sentiment-analysis/blob/master/C%20-%20Loading%2C%20Saving%20and%20Freezing%20Embeddings.ipynb) that covers how to load custom embeddings, train/fine-tune them on a task and then saving them afterwards so they can be loaded by TorchText again. 

Didn't have chance to read the paper, but I think this should be enough to cover what they're doing.

Let me know what you think.
