### ISSUE TITLE
use pre-trained word embeddings

### ISSUE THREAD

**Issue by DeeeepNet** [bentrevett/pytorch-sentiment-analysis#30]
Hi @bentrevett,
Q1. Can also use the pre-trained word embedding weights for non-sentiment analysis problem? such as machine translation or any problem related to text?
Q2. I want to work on searching with deep learning, in your opinion, if I have pre-trained word embedding when user pass a word, then the system gives us similarity words. Can get this similarity word from the pre-trained word embedding matrix?

**Comment by bentrevett** [comment]
Q1. Yes, you can use pre-trained embeddings for pretty much any NLP problem.

Q2. Yes, check out the [appendix b notebook](https://github.com/bentrevett/pytorch-sentiment-analysis/blob/master/B%20-%20A%20Closer%20Look%20at%20Word%20Embeddings.ipynb) which goes through using pre-trained embeddings for word similarity as well as using them for spelling correction.

**Comment by DeeeepNet** [comment]
Thanks,
I mean that Can I use the `glove.6b.100d` pre-trained weight for other issues of RNN, such as machine translation or......?

**Comment by DeeeepNet** [comment]
Thanks a lot,
If I want to solve searching with deep learning especially with RNNs, what're your ideas for this task? I created a website and I gathered a lot of content and loaded into the database of the server, My goal is if the user searches a keyword then the system find best of content for that, such as Google search, what're your ideas and suggestions about this?

**Comment by bentrevett** [comment]
I'm not really familiar with using deep learning for queries, sorry! 

I did a quick google and came across this book, [Deep Learning for Search](https://www.manning.com/books/deep-learning-for-search), which might be useful to you.

I know that Stanford also has an [Information Retrieval book](https://nlp.stanford.edu/IR-book/), although this isn't deep learning it might give useful background knowledge/ideas.

Your idea sounds interesting though, let me know how it goes!
