### ISSUE TITLE
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

### ISSUE THREAD

**Issue by vimalromeo** [bentrevett/pytorch-sentiment-analysis#32]
Hi,

I'm getting the error when I'm running the code to tokenize the text.
I've installed spacy and the English language model. I think the problem is that the spacy model is now called 'en_core_web_sm' instead of 'em'.

**Comment by bentrevett** [comment]
If anyone else finds this, the fix is to run the following on the command line after spacy has been installed:
```bash
python -m spacy download en
```
