### ISSUE TITLE
non consistent dropout after embeddings

### ISSUE THREAD

**Issue by 404akhan** [bentrevett/pytorch-sentiment-analysis#33]
In [2 - Updated Sentiment Analysis] you have dropout after embedding layer. 
In [4 - Convolutional Sentiment Analysis] you dont have dropout after embedding layer.
Not sure whether you need it, but this is inconsistent, you either do or dont need in both cases. I guess this is a mistake. So many mistakes dude, hah?

**Comment by bentrevett** [comment]
The 4th notebook is an implementation of the model from [this paper](https://arxiv.org/abs/1408.5882) which only has dropout after the max pooling. The 2nd notebook was just an introduction of concepts used in sentiment analysis, which does commonly use dropout on the embeddings so they're included there.

So no, it's not a mistake.
