### ISSUE TITLE
'tuple' object has no attribute 'permute' - 5Multi-Class Classification

### ISSUE THREAD

**Issue by saikiran2197** [bentrevett/pytorch-sentiment-analysis#34]
I get the following : AttributeError: 'tuple' object has no attribute 'permute' 
when trying to run the multi-class tutorial on my own data. 
![tuple](https://user-images.githubusercontent.com/28066754/56138950-cdd8a480-5f8f-11e9-89ce-3a7880507071.PNG)

Does anyone know what I am doing wrong here?

**Comment by Tomar9** [comment]
I am getting the same issue. Were you able to fix it? Could you please share the fix?

**Comment by bentrevett** [comment]
I think you are using `include_lengths = True` in your iterator, which means `batch.text` is now a tuple (two elements, first being the batch of numericalized tokens and the second being the batch of actual sequence lengths`). 

If you are using `include_lengths = True`, you need to separate the tuple by doing:

```python
text, text_lengths = batch.text
```
