### ISSUE TITLE
Question about Tutorial 4

### ISSUE THREAD

**Issue by labdmitriy** [bentrevett/pytorch-sentiment-analysis#35]
Hi Ben, 

Thanks a lot for this awesome tutorials!

I have a questions about tutorial 4 about CNN:

- On the 3rd picture max pooling is applied for 3 values (0.3, 0.6, 0.9), and you wrote that we pick 0.9 as maximum, but on the picture 0.3 is selected. Maybe it is a typo?

- Also in class implementation of CNN, after applying convolutional filters, there is a comment about conv_n shape:
#conv_n = [batch size, n_filters, sent len - filter_sizes[n]]
And in class implementation of CNN1d, there is a comment about the shape of the same output:
#conv_n = [batch size, n_filters, sent len - filter_sizes[n] - 1]
Do we have the 3rd dimension as "sent len - filter_sizes[n] + 1" in both cases?

Thank you.

**Comment by bentrevett** [comment]
Yep, those are both typos! It should be 0.9 and the conv_n sizes should all have a last dimension of *sent len - filter_sizes[n] + 1*. 

Sorry about that, will quickly push a fix now.
