### ISSUE TITLE
RuntimeError: 'lengths' array has to be sorted in decreasing order

### ISSUE THREAD

**Issue by HeoYoon** [bentrevett/pytorch-sentiment-analysis#37]
Hi!
I have tired to multi-class sentiment analysis.
You used CNN.
But I'd like to use other methods, so I coded it by Bi-LSTM.
But I got this error
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-84-c1b298b1eeea> in <module>
      7     start_time = time.time()
      8 
----> 9     train_loss, train_acc = train(model, train_iterator, optimizer, criterion)
     10     valid_loss, valid_acc = evaluate(model, valid_iterator, criterion)
     11 

<ipython-input-81-eba0e1173876> in train(model, iterator, optimizer, criterion)
     12         text, text_lengths = batch.text
     13 
---> 14         predictions = model(text, text_lengths).squeeze(1)
     15 
     16         loss = criterion(predictions, batch.label)

/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

<ipython-input-73-40263f80ab43> in forward(self, text, text_lengths)
     28 
     29         #pack sequence
---> 30         packed_embedded = nn.utils.rnn.pack_padded_sequence(embedded, text_lengths)
     31 
     32         packed_output, (hidden, cell) = self.rnn(packed_embedded)

/anaconda3/lib/python3.7/site-packages/torch/nn/utils/rnn.py in pack_padded_sequence(input, lengths, batch_first)
    146                       category=torch.jit.TracerWarning, stacklevel=2)
    147     lengths = torch.as_tensor(lengths, dtype=torch.int64)
--> 148     return PackedSequence(torch._C._VariableFunctions._pack_padded_sequence(input, lengths, batch_first))
    149 
    150 

RuntimeError: 'lengths' array has to be sorted in decreasing order

**Comment by bentrevett** [comment]
When using packed sequences your input sentences need to be sorted by their length, from longest to shortest. This means when defining your `BucketIterator` you need to set `sort_within_batch = True`. This will make TorchText return batches where the sentences are correctly sorted.

Saying that, in the latest version of PyTorch (1.1) you no longer need them sorted as long as you set `enforce_sorted` to `False` on the line where you pack the sequences, i.e.:

```python
packed_embedded = nn.utils.rnn.pack_padded_sequence(embedded, text_lengths, enforce_sorted = False)
```

**Comment by HeoYoon** [comment]
Thanks for comments
But, another error occured....
I added enforce_sorted = False 
I got this error :
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-292-be7c3f084aec> in <module>
      7     start_time = time.time()
      8 
----> 9     train_loss, train_acc = train(model, train_iterator, optimizer, criterion)
     10     valid_loss, valid_acc = evaluate(model, valid_iterator, criterion)
     11 

<ipython-input-289-3883fae45534> in train(model, iterator, optimizer, criterion)
     12         text, text_lengths = batch.text
     13 
---> 14         predictions = model(text, text_lengths).squeeze(1)
     15 
     16         loss = criterion(predictions, batch.label)

/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

<ipython-input-281-e36f78b24852> in forward(self, text, text_lengths)
     27 
     28         #pack sequence
---> 29         packed_embedded = nn.utils.rnn.pack_padded_sequence(embedded, text_lengths,enforce_sorted = False)
     30 
     31         packed_output, (hidden, cell) = self.rnn(packed_embedded)

/anaconda3/lib/python3.7/site-packages/torch/nn/utils/rnn.py in pack_padded_sequence(input, lengths, batch_first, enforce_sorted)
    266 
    267     data, batch_sizes = \
--> 268         torch._C._VariableFunctions._pack_padded_sequence(input, lengths, batch_first)
    269     return PackedSequence(data, batch_sizes, sorted_indices)
    270 

RuntimeError: Length of all samples has to be greater than 0, but found an element in 'lengths' that is <= 0

**Comment by bentrevett** [comment]
Have you checked the sizes of the tensors before they go into the `packed_padded_sequence` function? I believe the error you were having in your last issue (#36) was due to tensors of length zero in your dataset.

**Comment by HeoYoon** [comment]
I checked it, but tensor size is fine
And also it works well when using Fasttext and CNN.

**Comment by bentrevett** [comment]
Can you also check the `text_lengths` tensor has sensible values? Try printing it out before the packed padded sequences line.

**Comment by HeoYoon** [comment]
Thank you !!
I solved it.
But, do you know how can remove the empty element in train data?

**Comment by bentrevett** [comment]
You'll have to do a bit of debugging and see where the empty element is introduced. If I had to guess, it would be when you load in your data - which means it's either in the dataset or TorchText is tokenizing one of the examples incorrectly.
