### ISSUE TITLE
ValueError "too many values to unpack (expected 2)" due to "text, text_lengths = batch.text"

### ISSUE THREAD

**Issue by vincenttsai2015** [bentrevett/pytorch-sentiment-analysis#38]
I tried to run LSTM in "Updated Sentiment Analysis" with my own data, but the ValueError "too many values to unpack (expected 2)" occurs in "text, text_lengths = batch.text"......How can I fix it?
Isn't batch.text itself a set of batches containing tensors?  Why "text_lengths" is necessary? text_lengths=?

Thanks.

**Comment by bentrevett** [comment]
`batch.text` becomes a 2-element tuple when we use `include_lengths = True` in our `TEXT` field. We need to do this when using packed padded sequences as the LSTM needs to know the actual length of sentences without padding.

If you do not want to use packed padded sequences, then change `text, text_lengths = batch.text` to `text = batch.text` and remove all references to `text_lengths`. If you do want to use packed padded sequences, you need `include_lengths` set to `True` in your `TEXT` field.
