### ISSUE TITLE
embedding(): argument 'indices' (position 2) must be Tensor, not tuple

### ISSUE THREAD

**Issue by mehdiHadji** [bentrevett/pytorch-sentiment-analysis#39]
from Tutorials : 1 - Simple Sentiment Analysis
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-36-18c4bbde3ebb> in <module>()
      7     start_time = time.time()
      8 
----> 9     train_loss, train_acc = train(model, train_iterator, optimizer, criterion)
     10     valid_loss, valid_acc = evaluate(model, valid_iterator, criterion)
     11 

<ipython-input-32-cd15a9d80420> in train(model, iterator, optimizer, criterion)
     10         optimizer.zero_grad()
     11 
---> 12         predictions = model(batch.text).squeeze(1)
     13 
     14         loss = criterion(predictions, batch.label)

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

<ipython-input-24-4f665b3233dd> in forward(self, text)
     14         #text = [sent len, batch size]
     15 
---> 16         embedded = self.embedding(text)
     17 
     18         #embedded = [sent len, batch size, emb dim]

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/sparse.py in forward(self, input)
    116         return F.embedding(
    117             input, self.weight, self.padding_idx, self.max_norm,
--> 118             self.norm_type, self.scale_grad_by_freq, self.sparse)
    119 
    120     def extra_repr(self):

/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)
   1452         # remove once script supports set_grad_enabled
   1453         _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
-> 1454     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
   1455 
   1456 

TypeError: embedding(): argument 'indices' (position 2) must be Tensor, not tuple`

**Comment by bentrevett** [comment]
Did you set `required_lengths = True` in the `TEXT` field? This will cause `batch.text` to be a tuple of the numericalized text and the unpadded lenghts of the text. We only do this on notebook 2 as it uses packed padded sequences which required the actual text lengths. Notebook 1 does not require this.

**Comment by maliha-usui** [comment]
What if I get this error
TypeError: _make_subclass(): argument 'data' (position 2) must be Tensor, not tuple

**Comment by bentrevett** [comment]
@maliha-usui Do you have more of the error message?
