### ISSUE TITLE
You may notice that this tensor should have another dimension due to the one-hot vectors, however PyTorch conveniently stores a one-hot vector as it's index value, i.e. the tensor representing a sentence is just a tensor of the indexes for each token in that sentence.

### ISSUE THREAD

**Issue by dhecloud** [bentrevett/pytorch-sentiment-analysis#4]
> You may notice that this tensor should have another dimension due to the one-hot vectors, however PyTorch conveniently stores a one-hot vector as it's index value, i.e. the tensor representing a sentence is just a tensor of the indexes for each token in that sentence.

Hi, does this mean that when we train the model, we are feeding in the one-hot vectors, and not the value of the index?

I am feeding my array of characters into a 2d conv layer of filter size 20x256. Torchtext gives me (100,128) - 100 is sequence length, 128 is batch size. Was just wondering how to feed change the char vectors into one-hot

**Comment by bentrevett** [comment]
We feed in the indices, but these are "representing" the one hot vectors.

So for example if your vocabulary was something like:

``` 
"the": 0,
"cat": 1,
"sat": 2,
"on": 3,
"mat": 4
```

As indices, the sentence "the cat sat on the mat" would be **[0, 1, 2, 3, 0, 4]** and as one-hot vectors it would be: 
**[[1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0], [0,0,0,1,0], [1,0,0,0,0], [0,0,0,0,1]]**

In PyTorch, we can just feed the indexed versions of sentences to our models, we don't have to worry about converting to/from one-hot vectors. 

One-hot vectors are only mentioned them because it's a common way words are represented and I didn't want to not mention them at all.

**Comment by dhecloud** [comment]
@bentrevett Thanks for your quick reply.

Ok, i get your point. In that case, what should be the input shape into a convo layer? it should be `(batchsize, 1-channel, length of text)` right? I dont want to use any embedding as of yet

How then can conv2d work? Will changing to conv1d be wrong?

Thanks a lot for your help.

**Comment by bentrevett** [comment]
Ah ok, I think I misunderstood your question.

Yes, I think the best option is to change is to conv1d. I did a quick implementation and the following should work:

```
class CNN(nn.Module):
    def __init__(self, vocab_size, embedding_dim, n_filters, filter_sizes, output_dim, dropout):
        super().__init__()
        
        self.convs = nn.ModuleList([nn.Conv1d(in_channels=1, out_channels=n_filters, kernel_size=(fs)) for fs in filter_sizes])
        self.fc = nn.Linear(len(filter_sizes)*n_filters, output_dim)
        self.dropout = nn.Dropout(dropout)
        
    def forward(self, x):
        
        #x = [sent len, batch size]
        
        x = x.permute(1, 0)
                
        # = [batch size, sent len]
        
        x = x.unsqueeze(1)
        
        #x = [batch size, 1, sent len]
        
        conved = [F.relu(conv(x.float())) for conv in self.convs]
            
        #conv_n = [batch size, n_filters, sent len - filter_sizes[n]]
        
        pooled = [F.max_pool1d(conv, conv.shape[2]).squeeze(2) for conv in conved]
        
        #pooled_n = [batch size, n_filters]
        
        cat = self.dropout(torch.cat(pooled, dim=1))

        #cat = [batch size, n_filters * len(filter_sizes)]
            
        return self.fc(cat)
```

I'm not sure why you don't want to use an embedding layer though, I believe the results will be dramatically worse.

**Comment by dhecloud** [comment]
@bentrevett ah thanks a lot. i did not want to use embedding because well i was told not to haha. i got it running. thanks so much!
