### ISSUE TITLE
Can we save the vocabulary generated by torchtext for later prediction?

### ISSUE THREAD

**Issue by littleflow3r** [bentrevett/pytorch-sentiment-analysis#40]
Suppose I already saved the model and now want to use it only for inference, say to predict the sentiment of a sentence. We will need the vocabulary generated by torchtext to get the index of the words in the sentence we want to predict.
`
indexed = [TEXT.vocab.stoi[t] for t in tokenized]`

So is there a way to save torchtext vocabulary and re-load it (without the need to generate it again from the training data) ? 
To be clear, my question would be how to properly save the model (including everything it needs for inference), and then use it for 'independent' prediction?

Thanks!

**Comment by bentrevett** [comment]
I'm not currently aware of how to do this nicely in TorchText. 

I've been just saving the vocabulary used for training to a text file (tab separated):

``` python
def save_vocab(vocab, path):
    with open(path, 'w+') as f:     
        for token, index in vocab.stoi.items():
            f.write(f'{index}\t{token}')
```

Use this by passing `TEXT.vocab` to it.
         
Then, in the inference file, we can the vocabulary into a plain old Python dictionary:

``` python
def read_vocab(path):
    vocab = dict()
    with open(path, 'r') as f:
        for line in f:
            index, token = line.split('\t')
            vocab[token] = int(index)
    return vocab
```

Then use the below function - which is similar to that in the tutorials - which takes in a string, tokenizes it with our vocab we've just loaded and outputs a prediction.

``` python
def predict_sentiment(sentence, vocab, unk_idx):
    """
    sentence is string you wish to predict sentiment on
    vocab is dictionary, keys = tokens, values = index of token
    unk_idx is the index of the <unk> token in the vocab
    """
    tokens = tokenize(sentence) #convert string to tokens, needs to be same tokenization as training
    indexes = [vocab.get(t, unk_idx) for t in tokens] #converts to index or unk if not in vocab
    tensor = torch.LongTensor(indexes).unsqueeze(1) #convert to tensor and add batch dimension
    output = model(tensor) #get output from model
    prediction = torch.sigmoid(output) #squeeze between 0-1 range
    return prediction
```

This seems to be OK for all my needs, but I do wish TorchText had a way to load and save fields/vocab objects.

**Comment by littleflow3r** [comment]
Thanks! Using your method is more than enough for now! Yeah I was searching in the torchtext documentation and it seems there is currently no way to save the generated vocabulary.

**Comment by littleflow3r** [comment]
Sorry, one more question. If I used pretrained word embedding during training,
```
vec = vocab.Vectors('path to pretrained vector')
TEXT.build_vocab(train_dt, vectors=vec)
pretrained_vec = TEXT.vocab.vectors
```
and pass this to the model class,
`model = CNN(vocab_size, config, vec=pretrained_vec)`
do we also need to save this for inference?

**Comment by bentrevett** [comment]
Yep, these pre-trained vectors will be fine-tuned during training and thus will be different values to what they were originally. Thus, you'll have to save them at the end of training and then re-load them during inference.

**Comment by EmreTokyuez** [comment]
> I'm not currently aware of how to do this nicely in TorchText.
> 
> I've been just saving the vocabulary used for training to a text file (tab separated):
> 
> ```python
> def save_vocab(vocab, path):
>     with open(path, 'w+') as f:     
>         for token, index in vocab.stoi.items():
>             f.write(f'{index}\t{token}')
> ```
> 
> Use this by passing `TEXT.vocab` to it.
> 
> Then, in the inference file, we can the vocabulary into a plain old Python dictionary:
> 
> ```python
> def read_vocab(path):
>     vocab = dict()
>     with open(path, 'r') as f:
>         for line in f:
>             index, token = line.split('\t')
>             vocab[token] = int(index)
>     return vocab
> ```
> 
> Then use the below function - which is similar to that in the tutorials - which takes in a string, tokenizes it with our vocab we've just loaded and outputs a prediction.
> 
> ```python
> def predict_sentiment(model, sentence, vocab, unk_idx):
>     """
>     model is your PyTorch model
>     sentence is string you wish to predict sentiment on
>     vocab is dictionary, keys = tokens, values = index of token
>     unk_idx is the index of the <unk> token in the vocab
>     """
>     tokens = tokenize(sentence) #convert string to tokens, needs to be same tokenization as training
>     indexes = [vocab.get(t, unk_idx) for t in tokens] #converts to index or unk if not in vocab
>     tensor = torch.LongTensor(indexes).unsqueeze(1) #convert to tensor and add batch dimension
>     output = model(tensor) #get output from model
>     prediction = torch.sigmoid(output) #squeeze between 0-1 range
>     return prediction
> ```
> 
> This seems to be OK for all my needs, but I do wish TorchText had a way to load and save fields/vocab objects. The only other important thing is that the tokenization in the inference file needs to match that in the training file. If you tokenize your sentences differently then the vocabularies aren't going to match up and you'll get more unknown tokens than you should be getting.

When I do this, I get ValueError: too many values to unpack (expected 2) for the line index, token = line.split("\t"), why is that?

**Comment by mHsuann** [comment]
Sorry, I have a question about this.
After I do `TEXT.vocab = read_vocab(path)` and want to print `TEXT.stoi`, I got **AttributeError: 'dict' object has no attribute 'stoi'**. What happen about it?

Are there another solutions about loading field/vocab?

Thanks


> I'm not currently aware of how to do this nicely in TorchText.
> 
> I've been just saving the vocabulary used for training to a text file (tab separated):
> 
> ```python
> def save_vocab(vocab, path):
>     with open(path, 'w+') as f:     
>         for token, index in vocab.stoi.items():
>             f.write(f'{index}\t{token}')
> ```
> 
> Use this by passing `TEXT.vocab` to it.
> 
> Then, in the inference file, we can the vocabulary into a plain old Python dictionary:
> 
> ```python
> def read_vocab(path):
>     vocab = dict()
>     with open(path, 'r') as f:
>         for line in f:
>             index, token = line.split('\t')
>             vocab[token] = int(index)
>     return vocab
> ```
> 
> Then use the below function - which is similar to that in the tutorials - which takes in a string, tokenizes it with our vocab we've just loaded and outputs a prediction.
> 
> ```python
> def predict_sentiment(model, sentence, vocab, unk_idx):
>     """
>     model is your PyTorch model
>     sentence is string you wish to predict sentiment on
>     vocab is dictionary, keys = tokens, values = index of token
>     unk_idx is the index of the <unk> token in the vocab
>     """
>     tokens = tokenize(sentence) #convert string to tokens, needs to be same tokenization as training
>     indexes = [vocab.get(t, unk_idx) for t in tokens] #converts to index or unk if not in vocab
>     tensor = torch.LongTensor(indexes).unsqueeze(1) #convert to tensor and add batch dimension
>     output = model(tensor) #get output from model
>     prediction = torch.sigmoid(output) #squeeze between 0-1 range
>     return prediction
> ```
> 
> This seems to be OK for all my needs, but I do wish TorchText had a way to load and save fields/vocab objects. The only other important thing is that the tokenization in the inference file needs to match that in the training file. If you tokenize your sentences differently then the vocabularies aren't going to match up and you'll get more unknown tokens than you should be getting.

**Comment by aimanmutasem** [comment]
@mHsuann  any update? I have the same issue. :)

**Comment by bentrevett** [comment]
@EmreTokyuez

> When I do this, I get ValueError: too many values to unpack (expected 2) for the line index, token = line.split("\t"), why is that?

This is because one of the tokens in your vocabulary is the tab character, `\t`.

@mHsuann @aimanmutasem

> Sorry, I have a question about this.
After I do TEXT.vocab = read_vocab(path) and want to print TEXT.stoi, I got AttributeError: 'dict' object has no attribute 'stoi'. What happen about it?

This is because `read_vocab` here creates a dictionary and not a `Vocab` object. Hence why in the `predict_sentiment` function I wrote in this thread we use `vocab.get` and not `vocab.stoi`.

**Comment by aimanmutasem** [comment]
@bentrevett  correct, the new version could be as follow : 

```
def save_vocab(vocab, path):
    with open(path, 'w+') as f:     
        for token, index in vocab.stoi.items():
            f.write(f'{index}\t{token}\n')
```
Then : 

```
def read_vocab(path):
    vocab = dict()
    with open(path, 'r') as f:
        for line in f:
            index, token = line.split('\t')
            vocab[token] = int(index)
    return vocab
```
The weakness of this method it doesn't take the all variables of vector freqs,  stoi, and itos. 

Any suggestions?
