### ISSUE TITLE
Squeeze(0)

### ISSUE THREAD

**Issue by Ralphhorn** [bentrevett/pytorch-sentiment-analysis#41]
In tutorial 2 in the RNN.forward function you return self.fc(hidden.squeeze(0)).

However when I test this with my own data where I have a dataset of length x where x%batch_size ==1 it fails due to the removing of the dimension.

I printed out the hidden shape just before the return statement and noticed that the squeeze(0) is not needed as the hidden shape is of [batch_size,hidden_dim*num_directions].

My question is as follows: is it correct that the squeeze(0) is essentially not needed because it will always remove the batch_size dimension if it is 1?

Also awesome tutorial!

**Comment by bentrevett** [comment]
You're correct, that squeeze is unnecessary - not sure how that slipped in! Thanks for spotting it, will push a quick fix now.
