### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'fields'

### ISSUE THREAD

**Issue by Ravikiran2611** [bentrevett/pytorch-sentiment-analysis#42]
THE  FOLLOWING IS MY CODE
``` python
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
def token_split(data):
    return[text  for text in tokenizer.tokenize(data)]
Text = torchtext.data.Field(tokenize=token_split , pad_token= '[PAD]')
train_data = torchtext.data.TabularDataset.splits(path='./' ,train ='enron.csv' ,format ='csv',fields = [('text',Text)])
train_iterator = torchtext.data.Iterator(train_data,batch_size = 10,sort_key =lambda x: len(x.text), shuffle= True)
for example in train_iterator:
     print(example)
```

WHEN I RUN IT I GET THE FOLLOWING ERROR I AM NOT ABLE TO FINCD THE REASON CAN ANYONE HELP ME 
```
AttributeError: 'tuple' object has no attribute 'fields'
```

AND WHEN MY I USE 
``` python
train_iterator = torchtext.data.Iterator(train_data,batch_size = 10, shuffle= True)
```
I GET THIS ERROR ALSO
```
AttributeError: 'tuple' object has no attribute 'sort_key'
```
THANKS IN  ADVANCE

**Comment by bentrevett** [comment]
The issue here is that TorchText doesn't like it when you only provide training data and no test/validation data. `train_data` is a one element tuple containing your TabularDataset, instead of just being the TabularDataset itself.

A quick fix is to change the following line:
``` python
train_data = torchtext.data.TabularDataset.splits(path = './', train = 'enron.csv', format = 'csv', fields = [('text',Text)])
```
We can just make it read the same dataset again as a test dataset, but then never actually use it:
``` python
train_data, _ = torchtext.data.TabularDataset.splits(path = './', train ='enron.csv', test ='enron.csv', format = 'csv', fields = [('text',Text)])
```

**Comment by Ravikiran2611** [comment]
THANK YOU SO MUCH @bentrevett 
BUT NOW I GET  AN ERROR FOR THE FOLLOWING LINE
`for example in train_iterator:
     print(example)`

AttributeError: 'Field' object has no attribute 'vocab'
IS IT BECAUSE I HAVE NOT EXECUTED THE LINE 
Text.built_vocab(train_data)
IF SO  , IS THERE ANY WAY TO SET THE VOCAB TO THE VOCAB I HAVE BECAUSE I AM USING A PRETRAINED BERT , THAT IS ,IS IT POSSIBLE TO NUMERICALIZE USING THE BERT TOKENIZER
PLS REPLY IF THERE ANY OTHER WAY TO CREATE DATASET AND CREATE BATCHES FOR IT

**Comment by bentrevett** [comment]
Yep, that's the reason for your error. Unfortunately TorchText doesn't have a nice way to load existing vocabularies (yet). See: https://github.com/pytorch/text/issues/439 and https://github.com/pytorch/text/issues/555
