### ISSUE TITLE
Difference between Fast-Text model and Fast-Text embeddings

### ISSUE THREAD

**Issue by uccollab** [bentrevett/pytorch-sentiment-analysis#46]
In the third jupyter notebook it si shown how to implement the bi-gram based Fast-Text system to perform sentiment analysis. By looking up at the different embeddings that TorchText offers I have found that you can also use pre-trained Fast-Text vectors. How is this different from the implemented system? Would it be a nice idea to use the Fast-Text architecture with Fast-Text embeddings? Or maybe they could be used with other architectures, like RNN or LSTM?

**Comment by bentrevett** [comment]
I believe FastText is supposed to be a whole library of different architectures and embeddings, which (confusingly) all seem to use the FastText name.

The model implemented in the tutorial is detailed [here](https://fasttext.cc/docs/en/supervised-models.html) and the paper is [here](https://arxiv.org/abs/1607.01759). They refer to this model as `fastText`. 

Each of the embeddings has their own landing page on the FastText website, and at the bottom of each is a link to the paper detailing how these embeddings were trained. For example, [these](https://fasttext.cc/docs/en/english-vectors.html) embeddings use the architecture described in [this](https://arxiv.org/abs/1712.09405) paper. At the top of that page it states that "This page gathers several pre-trained word vectors trained using fastText." - however this reference to 'fastText' I believe refers to the library as a whole and not the fastText model implemented in these tutorials.

I'll admit I haven't done any experimenting with using the FastText vectors, I mostly stick to the Glove vectors - but if you do then let me know if you find any differences!
