### ISSUE TITLE
"cannot re-initialize cuda in forked subprocess. " + msg) 

### ISSUE THREAD

**Issue by EngSalem** [bentrevett/pytorch-sentiment-analysis#47]
I am getting this error
"cannot re-initialize cuda in forked subprocess. " + msg) 
When trying to iterate over the trainiteraor. In train function
I tried to change the device to cpu doesn't abd nothing happened 

Do you know where the error is stemming from?
I tried googling but wasn't able to solve it

**Comment by bentrevett** [comment]
I'm afraid I haven't encountered this error, sorry!

Do you have multiple GPUs on your machine?
