### ISSUE TITLE
ValueError: Target size (torch.Size([2, 1])) must be the same as input size (torch.Size([1, 1]))

### ISSUE THREAD

**Issue by Tomar9** [bentrevett/pytorch-sentiment-analysis#49]
Hi, 

Below is my error screenshot. Followed everything as you described in updated sentiment analysis. Just using my own dataset which has label categorized into 5 types.  

![image](https://user-images.githubusercontent.com/50909450/64059393-17542400-cbff-11e9-9c1e-074df14a807b.png)

Below is my code for fields definition and iterator.

`TEXT` = data.Field(tokenize = 'spacy', include_lengths = True)
LABEL = data.Field(dtype=torch.float)

fields = [('text', TEXT), ('label', LABEL)]

train_data, valid_data, test_data = data.TabularDataset.splits(
                                        path = r'H:\************',
                                        train = 'train.csv',
                                        validation = 'valid.csv',
                                        test = 'test.csv',
                                        format = 'csv',
                                        fields = `fields)`

`TEXT.build_vocab(train_data,`
                 vectors = "glove.6B.100d", 
                 unk_init = torch.Tensor.normal_)
LABEL.build_vocab(train_data)

import torch

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

BATCH_SIZE = 1

train_iterator, valid_iterator, test_iterator = data.BucketIterator.splits(
    (train_data, valid_data, test_data),
    sort_key = lambda x: x.text, #sort by s attribute (quote)
    sort_within_batch = True,
    batch_size=BATCH_SIZE,
    device=device)`

I tried to google it out but no luck. I am sorry I am new to the field, any help will be much appreciated. Could you please have a look let me know what could be creating this error?

**Comment by bentrevett** [comment]
You seem to have some issue where your target tensor has an extra element. Also, if you have 5 classes then your model should be outputting a tensor of size [1,5], whereas in the error it seems to be saying you're using a tensor of size [1,1].

Could you put all of your code in a .py file and upload it as a gist? It's difficult to debug without seeing the whole code.

**Comment by Tomar9** [comment]
Hi Ben,
The link to the gist having the whole code: 

https://gist.github.com/Tomar9/e577e3d1787b9b1129d52ca8773ea610

Could you please have a look and suggest changes?

**Comment by bentrevett** [comment]
A few issues:
- you say you have 5 categories for your data, which means your `OUTPUT_DIM` needs to be `5` and not `1`
- `BCEWithLogitsLoss` is only used for binary classification (2 classes) for >2 classes you need to use`nn.CrossEntropyLoss`
- `binary_accuracy` is also only used for binary classification, for >2 classes, see notebook 5 in this set of tutorials for a `categorical_accuracy` function that works for >2 classes

I am not 100% sure if this will fix the exact error you are having, but you will definitely need to do these at some point - so if you make these changes and post any new errors then we can work through them.

**Comment by Tomar9** [comment]
Sure. Thank you so much!! I will work on these changes and update you.

**Comment by Tomar9** [comment]
I did the suggested changes and was able to execute the code without any issues. Thank you for the support :)
