### ISSUE TITLE
2th Tutorial: ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by Lukang1994** [bentrevett/pytorch-sentiment-analysis#50]
I copy your demo,and use it in my computer ,but have the problem :
"train_data, valid_data = train_data.split(random_state = random.seed(SEED))
ValueError: not enough values to unpack (expected 2, got 0)"

**Comment by bentrevett** [comment]
I can't seem to recreate the error on my machine. Are you using the latest versions of PyTorch (1.2) and TorchText (0.4)?

**Comment by ydxu16** [comment]
same error here. Latest python pytorch and torchtext. Problem is datasets.IMDB.splits(Text, Label). This function return 0 train data and 21020 test_data

**Comment by ellemcfarlane** [comment]
for others who run into this issue, for me the cause was this https://github.com/pytorch/text/issues/667 -- I had interrupted "downloading aclImdb_v1.tar.gz" when it was at 100% because it was taking a very long time. This was the issue despite the fact that .data/imdb appeared to be all there.
