### ISSUE TITLE
<unk_init> in tutorial 2 Upgraded Sentiment Analysis

### ISSUE THREAD

**Issue by possible1402** [bentrevett/pytorch-sentiment-analysis#59]
In tutorial 2 upgraded sentiment analysis, you first initialize the token in vocabulary but not in pre-trained embeddings via a Gaussian distribution adding` unk_init` argument  insead of using the default value zero. But then you set their embedding weights to zero. I wanna ask why not initialize the value of `<unk>` and `<pad>` to zero at the first time?

**Comment by bentrevett** [comment]
The `<unk>` and `<pad>` tokens won't be the only ones not in the GloVe vocabulary. By setting the `unk_init` here we initialize every single token within our vocabulary, but not in the GloVe embeddings. Later on we then manually set the `<unk>` and `<pad>` tokens to zero.

Ideally, we would have a function that initializes the `<unk>` and `<pad>` tokens to zeros and the others not in GloVe to the Gaussian, but the `unk_init` argument is a bit specific in what it allows you to pass to it, so I don't think it's possible.

**Comment by possible1402** [comment]
Thanks a lot fo your reply. I thought that every single token within our vocabulary, but not in the GloVe embeddings would be replaced to `<unk>`. Because I found  BERT did that. Can you see if I understand correctly that every single token within our vocabulary, but not in the GloVe embeddings will remain unchangeable instead of being replaced to `<unk>`?

**Comment by bentrevett** [comment]
For tutorials 1-5: the vocabulary is created by counting the amount of times each token appears in the dataset and taking the 25,000 most common tokens. Each token within the vocabulary can be replaced by an integer index value, tokens not within the vocabulary can be replaced with an unk token. 

When we load the GloVe embeddings, a token which is in our vocabulary and also in the GloVe embeddings will be initialized to the value from the GloVe embeddings. A token within our vocabulary but not within GloVe embeddings is initialized by `unk_init`, i.e. from a Normal distributions. Our unk token, `<unk>` is not within the GloVe embeddings, therefore it is initialized with `unk_init`. I believe the confusion is the term `unk_init`, which doesn't refer to the unks in our vocabulary, but to tokens that are not within the GloVe embeddings. 

For tutorial 6: the BERT model already comes pretrained with its own vocabulary and embeddings. Tokens not within the vocabulary cannot be initialized to some `unk_init` type scheme as we are not initializing and training anything from scratch, only using the pre-trained weights.

Let me know if anything needs further clarifying!

**Comment by possible1402** [comment]
Thanks a lot for your reply!
