### ISSUE TITLE
Add Attention to the classification models

### ISSUE THREAD

**Issue by TharinduDR** [bentrevett/pytorch-sentiment-analysis#60]
Thank you for the wonderful repo and tutorials. 
Do you have an implementation to add attention to the classification models with torchtext?

**Comment by bentrevett** [comment]
If you know of any papers/models that have an attention based model for sequence classification, let me know and I can look into adding those. Usually attention is used for sequence-to-sequence learning, and I have some tutorials on that which use attention, see: https://github.com/bentrevett/pytorch-seq2seq tutorials 3 onwards.

**Comment by agoel15006** [comment]
https://arxiv.org/pdf/1409.0473.pdf

**Comment by bentrevett** [comment]
That model is for sequence-to-sequence learning, not sequence classification.

**Comment by TharinduDR** [comment]
Hi @bentrevett 
Was just checking on the issue - people have used it for many Kaggle competitions commonly. One such example is this - https://www.kaggle.com/hung96ad/pytorch-starter

**Comment by bentrevett** [comment]
Thanks for the link. Will check it out.

**Comment by karan121bhukar** [comment]
i want to work on this issue, is it still open?
