### ISSUE TITLE
Need to set "sort_key" in BucketIterator()? 

### ISSUE THREAD

**Issue by diavy** [bentrevett/pytorch-sentiment-analysis#64]
Thank you for your great codes illustration!

I noticed the following codes segment:

`train_iterator, valid_iterator, test_iterator = data.BucketIterator.splits(
    (train_data, valid_data, test_data), 
    batch_size = BATCH_SIZE,
    device = device)`

According to the official document:

> sort_key – A key to use for sorting examples in order to batch together examples with similar lengths and minimize padding.

So it seems that if you do not set the key, there's no difference between **Iterator** and **BucketIterator**. I also tested it myself, and confirmed it.

Could you please check it in your codes?

**Comment by bentrevett** [comment]
If you do not set a `sort_key` then TorchText will get the `sort_key` from the dataset, see [here](https://github.com/pytorch/text/blob/master/torchtext/data/iterator.py#L60).

The IMDB dataset used in these tutorials has it's sort key set [here](https://github.com/pytorch/text/blob/master/torchtext/datasets/imdb.py#L15), which is used by the `BucketIterator`.

**Comment by diavy** [comment]
Thank you, that's very helpful. BTW, could you please add the LSTM-CRF model in POS-TAGGING folder if possible? looking forward to it!

**Comment by bentrevett** [comment]
I'll look into it!
