### ISSUE TITLE
order of explanations on : "A - Using TorchText with Your Own Datasets"

### ISSUE THREAD

**Issue by antgr** [bentrevett/pytorch-sentiment-analysis#65]
I think that this is a bit confusing on a first read.
```Here, to access the name we use batch.n, to access the location we use batch.p, etc.```
but what are n, p, etc is explained later on
```fields = {'name': ('n', NAME), 'location': ('p', PLACE), 'quote': ('s', SAYING)}```

**Comment by bentrevett** [comment]
Updated this now. Let me know if it's clearer. TorchText is moving away from using `Fields`  and `Iterators` so that notebook will probably be obsolete in the next few months.

**Comment by antgr** [comment]
Yes, it is, thanks! Thanks for the info... Is torchtext supported officially by Facebook? I would like and expect more support which I do not see it, unfortunately. Although the guys that work on this, are awesome.

**Comment by bentrevett** [comment]
Yeah, it is an official library. I believe there is only a single person working on it, who also has other responsibilities, hence why it does not have great support.
