### ISSUE TITLE
application on dataset

### ISSUE THREAD

**Issue by shreyagopal** [bentrevett/pytorch-sentiment-analysis#66]
Thanks for the tutorial. 
Can this be applied on the other datasets which doesn't come with Pytorch?

**Comment by antgr** [comment]
Hi, yes you can. For example have a look at this tutorial, for using torch text to parse your dataset.
https://github.com/bentrevett/pytorch-sentiment-analysis/blob/master/A%20-%20Using%20TorchText%20with%20Your%20Own%20Datasets.ipynb

**Comment by bentrevett** [comment]
As @antgr mentioned, there is an "appendix" notebook which shows you how to load your own datasets. However, TorchText is moving away from using `Fields` and `Iterators` so that notebook will probably be obsolete in the next few months.

**Comment by shreyagopal** [comment]
Thanks for the suggestion. I applied the appendix notebook on the data i have but got an error of "Python int too large to convert to C long" while executing data.TabularDataset.splits(). Is there any solution for this??

**Comment by bentrevett** [comment]
I haven't encountered that error before. I believe it means there is a formatting issue in your data.
