### ISSUE TITLE
Why Hidden state instead output state?

### ISSUE THREAD

**Issue by jibinmathew691993** [bentrevett/pytorch-sentiment-analysis#8]
What is the intuition behind using hidden state from lstm/rnn instead of output state?

**Comment by bentrevett** [comment]
`output` is a tensor containing the hidden state at every single time-step, i.e. for every single word in the sentence. `hidden` is the hidden state at the final time-step, i.e. the final word in the sentence. 

You can think of `hidden` being a latent representation of the sentence so far. You only want to make a prediction after you have seen the whole sentence, hence we get the final hidden state (after the RNN has seen the whole sentence) which is `hidden`.

**Comment by jibinmathew691993** [comment]
output is the concatenation of the hidden state from every time step, whereas hidden is simply the final hidden state.

This line in the notebook made it look a little ambiguous. So if I understand right you mean to say that hidden state from the last RNN unit holds a representation from the entire sentence that should ideally be feed into fc, in comparison to which output is a tensor that is instantaneous, which combines the input and hidden state until that point to produce the corresponding output.

**Comment by bentrevett** [comment]
`hidden` is a tensor containing only the final hidden state, h_T, which we can say holds a representation of the entire sentence.

`output` is a tensor containing all of the hidden states, H = {h_1, h_2, ..., h_T}, where we can say each one holds a representation of the sentence so far, i.e. h_2 is a latent representation of the first two tokens in the sentence and h_T is a latent representation of the entire sequence which means it is equal to `hidden`. 

If we're predicting the sentiment of a sentence, we only want to do so after we have seen all the tokens in a sentence, hence we'll use the final hidden state, h_T, which is `hidden`. Alternatively we can get h_T by slicing into the `output` tensor, `output[-1::]`. These two tensors, `hidden` and `output[-1::]` are equal, which we prove using an `assert` statement in the code.

There are alternative ways to handle this, for example you can do a max or mean pooling operators over `output` and then feed that to the linear layer. This is done in tutorial 3.
