### ISSUE TITLE
Update tutorial with the new dataset

### ISSUE THREAD

**Issue by zhangguanheng66** [bentrevett/pytorch-sentiment-analysis#81]
Hey @bentrevett, Thanks for your tutorial. Since torchtext has updated the datasets with the new abstraction, I'm wondering if you plan to update the tutorial here. One of the users open an issue to follow your tutorial with the new dataset. Thanks. https://github.com/pytorch/text/issues/913

**Comment by bentrevett** [comment]
Hi @zhangguanheng66. Yes, I'm planning to update the tutorials to the new abstractions. They are currently in progress in the [experimental](https://github.com/bentrevett/pytorch-sentiment-analysis/tree/master/experimental) folder. Hopefully will have some time to put significant work into them during this week - should hopefully get all of the code done by then and I can focus adding the in-line explanations later.

Would be great to get your feedback on them when they're coded up, especially in terms of how my implementations align with your planned usage of the abstractions.
