### ISSUE TITLE
[FEATURE] Tutorials with pytorch-lightning

### ISSUE THREAD

**Issue by asvskartheek** [bentrevett/pytorch-sentiment-analysis#83]
Awesome tutorials! I was wondering if using pytorch-lightning can remove the amount of boilerplate code and can remove even the function to calculate time, by using a simple profiler flag on that library. If you think this is a good feature to add, I am interested to work on this.

**Comment by bentrevett** [comment]
I have no experience with pytorch-lightning myself, but have heard lots of good things. I'd be more than happy to accept a pull request that adds an extra notebook which goes through one of the tutorials using pytorch-lightning - I still want to keep the original tutorials using PyTorch and Torchtext only.

**Comment by asvskartheek** [comment]
Cool! I'll add it at as an addendum D notebook over the "FastText" model.
