### ISSUE TITLE
Copied Tutorial without credit to this repo

### ISSUE THREAD

**Issue by asvskartheek** [bentrevett/pytorch-sentiment-analysis#85]
I was going through random things related to text classification and found this [tutorial](https://www.analyticsvidhya.com/blog/2020/01/first-text-classification-in-pytorch/), it doesn't acknowledge this repository, most of the code is taken verbatim from this repository the dataset was different that is it.

**Comment by bentrevett** [comment]
Yeah, this seems to happen a lot. I've tried contacting the authors a few times but I never get a reply. 

In fairness, the repo here is under the MIT licence which doesn't require acknowledgement so there's nothing I can really do.

**Comment by bentrevett** [comment]
Thanks for pointing it out though!
