### ISSUE TITLE
2 - Upgraded Sentiment Analysis: TypeError: '<' not supported between instances of 'Example' and 'Example'

### ISSUE THREAD

**Issue by Junth** [bentrevett/pytorch-sentiment-analysis#88]
When working on the multiclass classification problem, **TypeError: '<' not supported between instances of 'Example' and 'Example'** has occurred. It has to do with BucketIterator sortkey  or something.
[BucketIterator](https://imgur.com/a/mbHNPlB)

**Comment by Junth** [comment]
![bucketiterator](https://user-images.githubusercontent.com/25685098/92566598-310d5a00-f29c-11ea-817d-1bd78b525871.PNG)

**Comment by bentrevett** [comment]
Are you using a custom dataset?

**Comment by Junth** [comment]
Yes, I figured that out, using sort_key in BucketIterator solves that problem but I think it lead to another error.
`RuntimeError: Length of all samples has to be greater than 0, but found an element in 'lengths' that is <= 0.`
