### ISSUE TITLE
Got error" 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor "

### ISSUE THREAD

**Issue by wwShuang** [bentrevett/pytorch-sentiment-analysis#93]
got error" 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor" when running the "2 - Upgraded Sentiment Analysis.ipynb" documents without changing
environment:
- ubuntu 18.04.5
- python --version 3.8.3
- Anaconda3-2020.07-Linux-x86_64
- gcc-4.8
- g++-4.8
- cuda-11.1
- pytorch-1.7.0
- torchtext-0.8.0

![Screenshot from 2020-11-11 18-02-04](https://user-images.githubusercontent.com/33902518/98797836-0ed4bb80-2448-11eb-923d-19ca52037cb5.png)

I tried to change pytorch version to 1.6 and 1.5 according to [pytorch/pytorch#16542 (comment)](url=https://github.com/pytorch/pytorch/issues/43227) but got another type of error(start with `from torchtext import data` ).

**Comment by bentrevett** [comment]
Can you try adding `.cpu()` after `text_lengths`? 

`packed_embedded = nn.utils.rnn.pack_padded_sequence(embedded, text_lengths.cpu())`?

**Comment by wwShuang** [comment]
Yes, @bentrevett  it works! thank you very much! You are brilliant!

**Comment by cjs2019** [comment]
I have encountered this problem recently. Thank you so much for your solutions and sharing.

**Comment by anjani-dhrangadhariya** [comment]
I get the issue `RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor` even after changing to `packed_input = pack_padded_sequence(b_masked_padded_sorted_output_, seq_lengths.cpu(), batch_first=True)`

**Comment by Faith-Uchiha** [comment]
i am running my ccode on gpu, if i try seq_lengths.cpu()   
another error occurs
`Input and hidden tensors are not at the same device, found input tensor at cuda:0 and hidden tensor at cpu`

can anyone help me?

**Comment by anjani-dhrangadhariya** [comment]
> i am running my ccode on gpu, if i try seq_lengths.cpu() another error occurs `Input and hidden tensors are not at the same device, found input tensor at cuda:0 and hidden tensor at cpu`
> 
> can anyone help me?

Could you please post the code so we can check?

**Comment by Faith-Uchiha** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您给我发送的邮件已收到。

**Comment by feifancoco** [comment]
> 这是来自QQ邮箱的自动回复邮件。   您好，您给我发送的邮件已收到。
请问一下，这个问题解决了吗？

**Comment by Faith-Uchiha** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您给我发送的邮件已收到。

**Comment by feifancoco** [comment]
我也正遇到这个问题，请教一下
