### ISSUE TITLE
where is the trained model parameters ?

### ISSUE THREAD

**Issue by fsalmasri** [bentrevett/pytorch-sentiment-analysis#94]
Is it possible to have the trained model params ?

**Comment by bentrevett** [comment]
For NLP models you can't just save the parameters, you also need to save the vocabulary and the tokenizer. 

I mainly wanted the tutorials to discuss how these models worked in terms of their architecture and how to build and train them with PyTorch - without going into the inference/deployment side. 

If you want to train a model yourself, use the Google Colab links as they have free access to GPUs if you go `Runtime > Change runtime type` and change the `Hardware accelerator` to `GPU`.
