### ISSUE TITLE
Pad Sequence error

### ISSUE THREAD

**Issue by georgezefko** [bentrevett/pytorch-sentiment-analysis#99]
I am trying to implement the tutorial on my own dataset which is sentiment analysis on twitter (text)data. 
I import the data according to the tutorial and i think this part is fine. However, when i run the code i get the following error

/usr/local/lib/python3.7/dist-packages/torch/nn/utils/rnn.py in pack_padded_sequence(input, lengths, batch_first, enforce_sorted)
    243 
    244     data, batch_sizes = \
--> 245         _VF._pack_padded_sequence(input, lengths, batch_first)
    246     return _packed_sequence_init(data, batch_sizes, sorted_indices, None)
    247 

**RuntimeError: Expected `len(lengths)` to be equal to batch_size, but got 32 (batch_size=22)**

Does anyone know how i can fix this?

**Comment by bentrevett** [comment]
Are you sure your tensors are the correct/shape size?

I would suggesting printing out the shapes of your data to see if it helps you debug the issue.

**Comment by georgezefko** [comment]
Thanks for the comment. The shapes are indeed problematic. Although i fixed the above error. Now I get a new one.

batch 
[torchtext.legacy.data.batch.Batch of size 32]
	[.id]:[torch.cuda.HalfTensor of size 1x32 (GPU 0)]
	[.target]:[torch.cuda.HalfTensor of size 1x32 (GPU 0)]
	[.text]:('[torch.cuda.LongTensor of size 23x32 (GPU 0)]', '[torch.cuda.LongTensor of size 32 (GPU 0)]')
target torch.Size([1, 32])
pred torch.Size([32])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-89-4e00e6ce4321> in <module>()
      7     start_time = time.time()
      8 
----> 9     train_loss, train_acc = train(model, train_iter, optimizer, criterion)
     10     valid_loss, valid_acc = evaluate(model, val_iter, criterion)
     11 

3 frames
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py in binary_cross_entropy_with_logits(input, target, weight, size_average, reduce, reduction, pos_weight)
   2822 
   2823     if not (target.size() == input.size()):
-> 2824         raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
   2825 
   2826     **return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)**

**ValueError: Target size (torch.Size([1, 32])) must be the same as input size (torch.Size([32]))**

It seems the error is BCEwithlogits due to different shapes in the predictions and batch.target.  
Any idea how this can be fixed.
